### PR TITLE
[PM-14936] Add AnonAddy self-hosted server URL support

### LINKED ISSUE #3152: Generating selfhosted addy.io username not possible in android app (works in browser extention)
### Steps To Reproduce

1. Open Bitwarden Android App
2. Click on Generator
3. Choose to generate username
4. Choose addy.io as Service
5. Server URL field missing

The Server URL field is available in the browser extension, but missing in the android app, not allowing to generate new users

### Expected Result

Server URL field showing

### Actual Result

Server URL field missing

### Screenshots or Videos

BW_Android
BW Android app with missing server URL entry field

BW_Browser_Ext
BW Browser extention with existing Server URL field.

### Additional Context

_No response_

### Operating System

Android

### Operating System Version

Android 14

### Device

Samsung Galaxy S22

### Build Version

2024.3.3

### Beta

- [ ] Using a pre-release version of the application.

### PR DESCRIPTION
**Pull request by SaintPatrck**
## 🎟️ Tracking

[PM-3553](https://bitwarden.atlassian.net/browse/PM-3553)
[PM-14936](https://bitwarden.atlassian.net/browse/PM-14936)
[PM-7430](https://bitwarden.atlassian.net/browse/PM-7430)

Resolves https://github.com/bitwarden/server/pull/5387
Resolves #3152
Relates to #4308

## 📔 Objective

Support self-hosted AnonAddy server URLs in the username generator.

When the feature flag, `AnonAddySelfHostAlias`, is enabled users can enter the server URL for their self-hosted AnonAddy instance. When disabled, the default cloud URL is used.

Self-hosted server URL is persisted with the other service type options.

Moved `prefixHttpsIfNecessaryOrNull` to `StringExtensions`.

## 📸 Screenshots

Coming soon!

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

[PM-14936]: https://bitwarden.atlassian.net/browse/PM-14936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-3503]: https://bitwarden.atlassian.net/browse/PM-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PM-3553]: https://bitwarden.atlassian.net/browse/PM-3553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-7430]: https://bitwarden.atlassian.net/browse/PM-7430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt [hunk 1]
```diff
@@ -2097,10 +2167,15 @@ data class GeneratorState(
                         data class AddyIo(
                             val apiAccessToken: String = "",
                             val domainName: String = "",
-                            val baseUrl: String = "https://app.addy.io",
+                            internal val selfHostServerUrl: String = "",
```
Comment (dseverns-livefront) [inline app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt:2170]: Is the `internal` scope doing anything here?

**Review by dseverns-livefront — APPROVED** [review]

File: app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt (hunk 1 above)
Comment (SaintPatrck) [reply app/src/main/java/com/x8bit/bitwarden/ui/tools/feature/generator/GeneratorViewModel.kt]: Nope. Thanks for catching that.

**Comment by SaintPatrck** [comment]
image
