### PR TITLE
[PM-22441] Refactor DigitalAssetLinkService to use source website

### LINKED ISSUE #5321: Ubank Passkey Issues Again - Private Space, Graphene OS
### Steps To Reproduce

1. Ubank and Bitwarden both installed in Private Space
2. Open uBank and try and sign in with passkey stored in Bitwarden
3. "An error has occured. Passkeys not supported for this app."

### Expected Result

1. Ubank and Bitwarden both installed in Private Space
2. Open uBank and try and sign in with passkey stored in Bitwarden
3. Sign in successful

### Actual Result

1. Ubank and Bitwarden both installed in Private Space
2. Open uBank and try and sign in with passkey stored in Bitwarden
3. "An error has occured. Passkeys not supported for this app."

### Screenshots or Videos

_No response_

### Additional Context

Worked fine previously, broken in most recent update: 2025.5.0 (20269)

### Build Version

2025.5.0 (20269)

### What server are you connecting to?

EU

### Self-host Server Version

_No response_

### Environment Details

- Pixel 9 Pro Fold
- Graphene OS [2025060200](https://grapheneos.org/releases#2025060200)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### LINKED ISSUE #5322: Login to 3rd party-app with Bitwarden-stored passkey fails
### Steps To Reproduce

1. Save passkey for 3rd party app in bitwarden
2. Try to log in to the app
3. Unlock Bitwarden
4. Error occurs

### Expected Result

Save passkey for 3rd party app in bitwarden
2. Try to log in to the app
3. Unlock Bitwarden
4. Successful Login

### Actual Result

Save passkey for 3rd party app in bitwarden
2. Try to log in to the app
3. Unlock Bitwarden
4. An error has occured. Passkeys not supported for this app

### Screenshots or Videos

The following two screenshots show the error messages (in german) that occur when we try to sign in with a passkey in the newest update. The first error message originates from the os and the second one from the 3rd party app.
Image

Image

### Additional Context

This problem is definitely tied to the new version 2025.5.0. We expierienced this issue on multiple devices.
On devices with the old version 2025.4.0 the login with passkeys works flawlessly.
Deleting passkeys, reinstalling apps, reseting devices didn't solve the issue.

### Build Version

2025.5.0

### What server are you connecting to?

US

### Self-host Server Version

_No response_

### Environment Details

Devices: Samsung Galaxy A30s series
OS: Stock Android 14 up to date

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by SaintPatrck**
## 🎟️ Tracking

PM-22441
Closes #5321
Closes #5322

## 📔 Objective

The `DigitalAssetLinkService` and its implementation now take a `sourceWebSite` parameter instead of relying on the target application's package name and certificate fingerprint for the source. This aligns better with how Digital Asset Links work, where the website declares trust in the app.

The `OriginManager` now passes the `relyingPartyId` (which is the source website) to the `DigitalAssetLinkService`.

A `RelyingPartyParser` interface and its implementation `RelyingPartyParserImpl` have been introduced to centralize the logic for parsing relying party IDs from various Credential Manager request objects.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt [hunk 1]
```diff
@@ -136,6 +138,7 @@ class VaultItemListingViewModel @Inject constructor(
     private val organizationEventManager: OrganizationEventManager,
     private val networkConnectionManager: NetworkConnectionManager,
     private val snackbarRelayManager: SnackbarRelayManager,
+    private val json: Json,
```
Comment (david-livefront) [inline app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt]: It feels a little odd to have a Json instance in the ViewModel.

Do you think a RelayingIdParser class would be better, an injectable manager class that would have the Json injected into it and would have functions similar to all those extensions?

Comment (SaintPatrck) [reply app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt]: I was debating that, actually. I'm for it. 🚀

File: app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt [hunk 2]
```diff
@@ -136,6 +137,7 @@ class VaultItemListingViewModel @Inject constructor(
     private val organizationEventManager: OrganizationEventManager,
     private val networkConnectionManager: NetworkConnectionManager,
     private val snackbarRelayManager: SnackbarRelayManager,
+    private val relyingPartyParser: RelyingPartyParser,
```
Comment (david-livefront) [inline app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt:140]: This feels better to me, thanks for making the update!

Comment (SaintPatrck) [reply app/src/main/kotlin/com/x8bit/bitwarden/ui/vault/feature/itemlisting/VaultItemListingViewModel.kt:140]: Same. I think we can use this pattern to cleanup the Credential Manager request handling even more. 🚀

**Comment by Nailik** [comment]
very nice 👍
