### PR TITLE
[PM-24700] Update email validation in LandingViewModel

### LINKED ISSUE #5687: [PM-24700] Invalid email address received when email address contains | and =
### Steps To Reproduce

1. Create Bitwarden account with the | and = character in the email address
2. Attempt to sign in to the Bitwarden Android app

### Expected Result

Can sign in successfully

### Actual Result

Receive "Invalid email address" error message

### Screenshots or Videos

_No response_

### Additional Context

The email address I use for Bitwarden contains a "|" and a "=" in the local address.  The desktop client has no problem with the email address and I receive have received email from Bitwarden at it, but the Android app started giving me the "invalid email address" error a while ago.

I found https://github.com/bitwarden/android/issues/5535 while trying to resolve the issue and I would ask you to add these special characters as well. 

### Build Version

2025.7.2 (20551)

### What server are you connecting to?

US

### Self-host Server Version

_No response_

### Environment Details

- Pixel 7
- Android 16

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by SaintPatrck**
## 🎟️ Tracking

PM-24700
Resolves #5687

## 📔 Objective

The email validation in `LandingViewModel` was updated to use non-strict validation. The `isValidEmail` extension function was also updated to include a `useStrictValidation` parameter to control the validation behavior.

## 📸 Screenshots

https://github.com/user-attachments/assets/4ad569fc-bb48-4feb-b7ef-9fc808a4b5ce

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt [hunk 1]
```diff
@@ -180,7 +180,7 @@ class LandingViewModel @Inject constructor(
     }
 
     private fun handleContinueButtonClicked() {
-        if (!state.emailInput.isValidEmail()) {
+        if (!state.emailInput.isValidEmail(useStrictValidation = false)) {
```
Comment (david-livefront) [inline app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt:183]: Why are we doing it different here than other places?

Comment (SaintPatrck) [reply app/src/main/kotlin/com/x8bit/bitwarden/ui/auth/feature/landing/LandingViewModel.kt:183]: Backwards compatibility, according to https://bitwarden.atlassian.net/browse/PM-24730. Going forward we need to enforce what we consider valid email addresses during registration but because that has not been done correctly in the past there are users with "invalid" email addresses that we must allow to log in.
