### PR TITLE
[PM-21585] Display item folder location when only in a single folder

### LINKED ISSUE #5183: Folder is not shown in the View Login screen
### Steps To Reproduce

1. Create a new login without assigning it to a folder (select No folder when creating it)
2. Go to the View Login screen to view it
3. Edit the login and assign it to a folder 
4. Go to the View Login screen to view it

### Expected Result

Whether the login is assigned to a folder, the folder bar should be shown in the View Login screen

### Actual Result

The folder bar is only shown when it's assigned to No Folder.

### Screenshots or Videos

_No response_

### Additional Context

_No response_

### Build Version

 2025.4.0 (20100)

### What server are you connecting to?

US

### Self-host Server Version

_No response_

### Environment Details

© Bitwarden Inc. 2015-2025

Version: 2025.4.0 (20100)
🧱 commit: bitwarden/android/release/2025.04-rc19@bee09de972c3870de0d54a0067996be473ec55c7
💻 build source: bitwarden/android/actions/runs/14536896217/attempts/1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

### PR DESCRIPTION
**Pull request by SaintPatrck**
## 🎟️ Tracking

PM-21585
Closes #5183 

## 📔 Objective

Display an item's folder location in the item header when the item is only assigned to a single folder and not any collections.

A new preview has also been added to demonstrate this change.

## 📸 Screenshots

| Before | After |
|--------|--------|
| image |image | 

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

File: app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/ItemHeader.kt [hunk 1]
```diff
@@ -485,4 +507,27 @@ private fun ItemNameField_Org_SingleCollection_Folder_Preview() {
         }
     }
 }
+
+@Composable
+@Preview
+private fun ItemNameField_Folder_Only_Preview() {
```
Comment (david-livefront) [inline app/src/main/java/com/x8bit/bitwarden/ui/vault/feature/item/component/ItemHeader.kt:513]: I think this should be `ItemNameFieldFolderOnly_Preview` based on other previews in the app

**Review by david-livefront — APPROVED** [review]
